# Generated by Django 4.0 on 2021-12-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.TextField()),
                ('name', models.TextField()),
                ('brand', models.TextField()),
                ('make', models.TextField()),
                ('description', models.TextField()),
                ('year', models.TextField()),
                ('CPCODE', models.TextField()),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
