# Generated by Django 4.0.2 on 2022-02-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_apis', '0002_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('priority', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Todo',
            },
        ),
        migrations.DeleteModel(
            name='products',
        ),
    ]
